



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// 
//     Tool     : bondc, Version=3.0.1, Build=bond-git.retail.directory
//     Template : Microsoft.Bond.Rules.dll#Rules_Bond_CSharp.tt
//     File     : PSCFRSpark_types.cs
//
//     Changes to this file may cause incorrect behavior and will be lost when
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using global::Microsoft.Bond;
using global::System;
using global::System.Collections;
using global::System.Collections.Generic;
using global::System.Text;

namespace SparkSchema
{

/// <summary>
/// PSCFRSpark
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("bondc.exe", null)]
public partial class PSCFRSpark : IBondSerializable, IGenericSerializer
{
    //
    // Fields
    //

    // 1: Optional blob PageView
    private BondBlob m_PageView;

    // 2: Optional blob AdImpression
    private BondBlob m_AdImpression;

    // 3: Optional blob Click
    private BondBlob m_Click;

    // 4: Optional blob FraudInfo
    private BondBlob m_FraudInfo;

    /// <summary>
    /// PageView
    /// </summary>
    public BondBlob PageView
    {
        get { return this.m_PageView; }
        set { this.m_PageView = value; }
    }

    /// <summary>
    /// AdImpression
    /// </summary>
    public BondBlob AdImpression
    {
        get { return this.m_AdImpression; }
        set { this.m_AdImpression = value; }
    }

    /// <summary>
    /// Click
    /// </summary>
    public BondBlob Click
    {
        get { return this.m_Click; }
        set { this.m_Click = value; }
    }

    /// <summary>
    /// FraudInfo
    /// </summary>
    public BondBlob FraudInfo
    {
        get { return this.m_FraudInfo; }
        set { this.m_FraudInfo = value; }
    }

    /// <summary>
    /// GetFullyQualifiedName
    /// </summary>
    public static string GetFullyQualifiedName()
    {
        return __internal.sc_structQualifiedName;
    }

    /// <summary>
    /// Meta schema.
    /// </summary>
    private static class Schema
    {
        public static readonly Metadata meta = new Metadata();
        public static readonly Metadata PageView_meta = new Metadata();
        public static readonly Metadata AdImpression_meta = new Metadata();
        public static readonly Metadata Click_meta = new Metadata();
        public static readonly Metadata FraudInfo_meta = new Metadata();

        static Schema()
        {
            StringBuilder runtimeName = new StringBuilder();
            runtimeName.Append("PSCFRSpark");
 
            meta.name = runtimeName.ToString();
            meta.qualified_name = "SparkSchema." + meta.name;


            // PageView
            PageView_meta.name = "PageView";
            PageView_meta.modifier = global::Microsoft.Bond.Modifier.Optional;

            // AdImpression
            AdImpression_meta.name = "AdImpression";
            AdImpression_meta.modifier = global::Microsoft.Bond.Modifier.Optional;

            // Click
            Click_meta.name = "Click";
            Click_meta.modifier = global::Microsoft.Bond.Modifier.Optional;

            // FraudInfo
            FraudInfo_meta.name = "FraudInfo";
            FraudInfo_meta.modifier = global::Microsoft.Bond.Modifier.Optional;
        }   // ~static Schema()

    }   // ~Schema


    private static class __ordinals
    {
        public const int PageView = 1;
        public const int AdImpression = 2;
        public const int Click = 3;
        public const int FraudInfo = 4;
    }   // ~__ordinals


    private static class __internal
    {

        public static readonly String sc_structName = Schema.meta.name;
        public static readonly String sc_structQualifiedName = Schema.meta.qualified_name;

        public const String s_PageView = "PageView";
        public const String s_AdImpression = "AdImpression";
        public const String s_Click = "Click";
        public const String s_FraudInfo = "FraudInfo";
    }   // ~__internal

    /// <summary>
    /// Constructor
    /// </summary>
    public PSCFRSpark()
    {
        Reset();
    }

    /// <summary>
    /// Reset instance and re-initialize the members.
    /// </summary>
    public virtual void Reset()
    {
        Reset(__internal.sc_structName, __internal.sc_structQualifiedName);
    }

    /// <summary>
    /// Reset
    /// </summary>
    protected  void Reset(string name, string qualifiedName)
    {
        
        ResetImpl(name, qualifiedName);
    }

    private void ResetImpl(string name, string qualifiedName)
    {
        m_PageView = default(BondBlob);
        m_AdImpression = default(BondBlob);
        m_Click = default(BondBlob);
        m_FraudInfo = default(BondBlob);
    } // ResetImpl()

    /// <summary>
    /// Clone
    /// </summary>
    public virtual IBondSerializable Clone()
    {
        global::SparkSchema.PSCFRSpark cloned = new global::SparkSchema.PSCFRSpark();
        CopyTo(cloned);
        return cloned;
    }

    /// <summary>
    /// CopyTo
    /// </summary>
    public void CopyTo(global::SparkSchema.PSCFRSpark that)
    {
        if (that == null)
        {
            throw new  ArgumentNullException("that");
        }
        
        // 1: blob PageView
        that.PageView = this.PageView.CloneData();
        // 2: blob AdImpression
        that.AdImpression = this.AdImpression.CloneData();
        // 3: blob Click
        that.Click = this.Click.CloneData();
        // 4: blob FraudInfo
        that.FraudInfo = this.FraudInfo.CloneData();
    }    // ~CopyTo


    /// <summary>
    /// Unmarshal
    /// </summary>
    public virtual void Unmarshal(System.IO.Stream input)
    {
        global::Microsoft.Bond.Marshaler.Unmarshal(input, this);
    }

    /// <summary>
    /// Unmarshal
    /// </summary>
    public virtual void Unmarshal(System.IO.Stream input, IBondSerializable schema)
    {
        global::Microsoft.Bond.Marshaler.Unmarshal(input, schema as SchemaDef, this);
    }

    /// <summary>
    /// Read
    /// </summary>
    public virtual void Read(global::Microsoft.Bond.IProtocolReader reader)
    {
        if (!reader.HasCapability(global::Microsoft.Bond.Protocol.Tagged))
        {
            ReadUntagged(reader);
        }
        else
        {
            bool isPartialStruct;

            if (reader.HasCapability((global::Microsoft.Bond.Protocol)global::Microsoft.Bond.ProtocolInternal.CloneableBonded))
            {
                reader = reader.Clone();
            }
            
            Read(reader, out isPartialStruct);
            
            if (isPartialStruct)
            {
                global::Microsoft.Bond.ReadHelper.SkipPartialStruct(reader);
            }
        }
    }

    /// <summary>
    /// Read
    /// </summary>
    public virtual void Read(global::Microsoft.Bond.IProtocolReader reader, IBondSerializable schema)
    {
        Read(ProtocolHelper.CreateReader(reader, schema));
    }

    /// <summary>
    /// ReadUntagged
    /// </summary>
    protected  void ReadUntagged(global::Microsoft.Bond.IProtocolReader reader)
    {
        bool canOmitFields = reader.HasCapability(global::Microsoft.Bond.Protocol.CanOmitFields);
        Reset();
        

        reader.ReadStructBegin();

        if (!canOmitFields || !reader.ReadFieldOmitted())
        {
            this.PageView = this.PageView.FromData(global::Microsoft.Bond.ReadHelper.ReadBlob(reader, global::Microsoft.Bond.BondDataType.BT_LIST));
        }

        if (!canOmitFields || !reader.ReadFieldOmitted())
        {
            this.AdImpression = this.AdImpression.FromData(global::Microsoft.Bond.ReadHelper.ReadBlob(reader, global::Microsoft.Bond.BondDataType.BT_LIST));
        }

        if (!canOmitFields || !reader.ReadFieldOmitted())
        {
            this.Click = this.Click.FromData(global::Microsoft.Bond.ReadHelper.ReadBlob(reader, global::Microsoft.Bond.BondDataType.BT_LIST));
        }

        if (!canOmitFields || !reader.ReadFieldOmitted())
        {
            this.FraudInfo = this.FraudInfo.FromData(global::Microsoft.Bond.ReadHelper.ReadBlob(reader, global::Microsoft.Bond.BondDataType.BT_LIST));
        }
        reader.ReadStructEnd();
    }   // ~ReadUntagged()


    /// <summary>
    /// Read
    /// </summary>
    protected  void Read(global::Microsoft.Bond.IProtocolReader reader, out bool isPartialStruct)
    {
        Reset();

        reader.ReadStructBegin(true);
        
        while (true)
        {
            BondDataType type = BondDataType.BT_STOP;
            UInt16 id = UInt16.MaxValue;

            reader.ReadFieldBegin(out type, out id);

            if (type == BondDataType.BT_STOP || type == BondDataType.BT_STOP_BASE)
            {
                isPartialStruct = (type == BondDataType.BT_STOP_BASE);
                break;
            }

            switch (id)
            {
                case __ordinals.PageView:  // id=1
                    this.PageView = global::Microsoft.Bond.ReadHelper.ReadBlob(reader, type);
                    break;
                case __ordinals.AdImpression:  // id=2
                    this.AdImpression = global::Microsoft.Bond.ReadHelper.ReadBlob(reader, type);
                    break;
                case __ordinals.Click:  // id=3
                    this.Click = global::Microsoft.Bond.ReadHelper.ReadBlob(reader, type);
                    break;
                case __ordinals.FraudInfo:  // id=4
                    this.FraudInfo = global::Microsoft.Bond.ReadHelper.ReadBlob(reader, type);
                    break;
                default:
                    reader.Skip(type);
                    break;
            } // ~switch

            reader.ReadFieldEnd();

        } // ~while

        reader.ReadStructEnd();

    }   // ~Read()


    /// <summary>
    /// Marshal
    /// </summary>
    virtual public void Marshal(IProtocolWriter writer)
    {
        global::Microsoft.Bond.Marshaler.Marshal(this, writer);
    }

    /// <summary>
    /// Write
    /// </summary>
    virtual public void Write(global::Microsoft.Bond.IProtocolWriter writer)
    {
        Write(writer, true);
    }

    /// <summary>
    /// Write
    /// </summary>
    public void Write(global::Microsoft.Bond.IProtocolWriter writer, bool isTopLevel)
    {
        global::Microsoft.Bond.IProtocolWriter pass0; 
        
        if (isTopLevel && (pass0 = writer.GetPass0Writer()) != null)
        {
            WriteInternal(pass0, isTopLevel);
            WriteInternal(writer, isTopLevel);
            writer.EndDoublePass();
        }
        else
        {
            WriteInternal(writer, isTopLevel);
        }
    }   // ~Write()

    /// <summary>
    /// Write
    /// </summary>
    virtual public void Write(global::Microsoft.Bond.IProtocolWriter writer, System.Type type)
    {
        if (type == typeof(PSCFRSpark))
        {
            Write(writer, true);
        }
    }

    /// <summary>
    /// WriteInternal
    /// </summary>
    protected void WriteInternal(global::Microsoft.Bond.IProtocolWriter writer, bool isTopLevel)
    {
	                

        bool writeAllFields = !writer.MayOmitFields;

        writer.WriteStructBegin(Schema.meta, !isTopLevel, true);

        UInt32 count1 = (m_PageView == null ? 0 : m_PageView.GetCount());
        if (writeAllFields || m_PageView != null)
        {
            writer.WriteFieldBegin(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.PageView, Schema.PageView_meta);
                writer.WriteContainerBegin(count1, BondDataType.BT_INT8);
            writer.WriteBlob(m_PageView.GetData());
            writer.WriteContainerEnd();
            writer.WriteFieldEnd();
        }
        else
        {
            writer.WriteFieldOmitted(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.PageView, Schema.PageView_meta);
        }

        UInt32 count2 = (m_AdImpression == null ? 0 : m_AdImpression.GetCount());
        if (writeAllFields || m_AdImpression != null)
        {
            writer.WriteFieldBegin(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.AdImpression, Schema.AdImpression_meta);
                writer.WriteContainerBegin(count2, BondDataType.BT_INT8);
            writer.WriteBlob(m_AdImpression.GetData());
            writer.WriteContainerEnd();
            writer.WriteFieldEnd();
        }
        else
        {
            writer.WriteFieldOmitted(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.AdImpression, Schema.AdImpression_meta);
        }

        UInt32 count3 = (m_Click == null ? 0 : m_Click.GetCount());
        if (writeAllFields || m_Click != null)
        {
            writer.WriteFieldBegin(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.Click, Schema.Click_meta);
                writer.WriteContainerBegin(count3, BondDataType.BT_INT8);
            writer.WriteBlob(m_Click.GetData());
            writer.WriteContainerEnd();
            writer.WriteFieldEnd();
        }
        else
        {
            writer.WriteFieldOmitted(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.Click, Schema.Click_meta);
        }

        UInt32 count4 = (m_FraudInfo == null ? 0 : m_FraudInfo.GetCount());
        if (writeAllFields || m_FraudInfo != null)
        {
            writer.WriteFieldBegin(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.FraudInfo, Schema.FraudInfo_meta);
                writer.WriteContainerBegin(count4, BondDataType.BT_INT8);
            writer.WriteBlob(m_FraudInfo.GetData());
            writer.WriteContainerEnd();
            writer.WriteFieldEnd();
        }
        else
        {
            writer.WriteFieldOmitted(global::Microsoft.Bond.BondDataType.BT_LIST, __ordinals.FraudInfo, Schema.FraudInfo_meta);
        }

        writer.WriteStructEnd(!isTopLevel);
    }   // ~Write()

    private static volatile global::Microsoft.Bond.SchemaDef __schema;

    /// <summary>
    /// GetSchema
    /// </summary>
    public virtual IBondSerializable GetSchema()
    {
        return GetRuntimeSchema();
    }

    /// <summary>
    /// GetRuntimeSchema
    /// </summary>
    static public global::Microsoft.Bond.SchemaDef GetRuntimeSchema()
    {
        if (__schema == null)
        {
            var schema = new global::Microsoft.Bond.SchemaDef();
            schema.root = GetTypeDef(schema);
            __schema = schema;
        }
        return __schema;
    }

    /// <summary>
    /// GetTypeDef
    /// </summary>
    static public global::Microsoft.Bond.TypeDef GetTypeDef(global::Microsoft.Bond.SchemaDef schema)
    {
        global::Microsoft.Bond.TypeDef type = new global::Microsoft.Bond.TypeDef();
        type.id = global::Microsoft.Bond.BondDataType.BT_STRUCT;
        type.struct_def = GetStructDef(schema);
        return type;
    }

    /// <summary>
    /// GetTypeDef
    /// </summary>
    static protected UInt16 GetStructDef(global::Microsoft.Bond.SchemaDef schema)
    {
        UInt16 pos;

        for(pos = 0; pos < schema.structs.Count; pos++)
        {
            if (schema.structs[pos].metadata.qualified_name == __internal.sc_structQualifiedName)
            {
                return pos;
            }
        }
        // pos == schema.structs.Count

        global::Microsoft.Bond.StructDef structDef = new global::Microsoft.Bond.StructDef();
        structDef.metadata.name = __internal.sc_structName;
        structDef.metadata.qualified_name = __internal.sc_structQualifiedName;
        schema.structs.Add(structDef);

        global::Microsoft.Bond.FieldDef field;


        field = new global::Microsoft.Bond.FieldDef();
        field.id = 1;
        field.metadata.name="PageView";
        field.metadata.modifier = global::Microsoft.Bond.Modifier.Optional;
        field.metadata.default_value.nothing = true;

        field.type.id = global::Microsoft.Bond.BondDataType.BT_LIST;
        field.type.element = new global::Microsoft.Bond.TypeDef();
        field.type.element.id = global::Microsoft.Bond.BondDataType.BT_INT8;

        structDef.fields.Add(field);

        field = new global::Microsoft.Bond.FieldDef();
        field.id = 2;
        field.metadata.name="AdImpression";
        field.metadata.modifier = global::Microsoft.Bond.Modifier.Optional;
        field.metadata.default_value.nothing = true;

        field.type.id = global::Microsoft.Bond.BondDataType.BT_LIST;
        field.type.element = new global::Microsoft.Bond.TypeDef();
        field.type.element.id = global::Microsoft.Bond.BondDataType.BT_INT8;

        structDef.fields.Add(field);

        field = new global::Microsoft.Bond.FieldDef();
        field.id = 3;
        field.metadata.name="Click";
        field.metadata.modifier = global::Microsoft.Bond.Modifier.Optional;
        field.metadata.default_value.nothing = true;

        field.type.id = global::Microsoft.Bond.BondDataType.BT_LIST;
        field.type.element = new global::Microsoft.Bond.TypeDef();
        field.type.element.id = global::Microsoft.Bond.BondDataType.BT_INT8;

        structDef.fields.Add(field);

        field = new global::Microsoft.Bond.FieldDef();
        field.id = 4;
        field.metadata.name="FraudInfo";
        field.metadata.modifier = global::Microsoft.Bond.Modifier.Optional;
        field.metadata.default_value.nothing = true;

        field.type.id = global::Microsoft.Bond.BondDataType.BT_LIST;
        field.type.element = new global::Microsoft.Bond.TypeDef();
        field.type.element.id = global::Microsoft.Bond.BondDataType.BT_INT8;

        structDef.fields.Add(field);

        return pos;
    }
 
    /// <summary>
    /// MemberwiseCompare
    /// </summary>
    public virtual bool MemberwiseCompare(object obj)
    {
        if (obj == null)
        {
            return false;
        }
        
        PSCFRSpark that = obj as PSCFRSpark;
        if (that == null)
        {
            return false;
        }
        
        return this.MemberwiseCompare(that);
    }
    
    /// <summary>
    /// MemberwiseCompare
    /// </summary>
    public bool MemberwiseCompare(PSCFRSpark other)
    {
        if (!MemberwiseCompareQuick(other))
        {
            return false;
        }
        
        return MemberwiseCompareDeep(other);
    }
    

    /// <summary>
    /// MemberwiseCompareQuick
    /// </summary>
    protected bool MemberwiseCompareQuick(PSCFRSpark that)
    {
        bool equals = true;
        
        equals = equals && (this.PageView.GetCount() == that.PageView.GetCount());
        equals = equals && (this.AdImpression.GetCount() == that.AdImpression.GetCount());
        equals = equals && (this.Click.GetCount() == that.Click.GetCount());
        equals = equals && (this.FraudInfo.GetCount() == that.FraudInfo.GetCount());
        return equals;
    }    // ~MemberwiseCompareQuick
    
    /// <summary>
    /// MemberwiseCompareDeep
    /// </summary>
    protected bool MemberwiseCompareDeep(PSCFRSpark that)
    {
        bool equals = true;
        
        equals = equals && this.PageView.CompareData(that.PageView);
        equals = equals && this.AdImpression.CompareData(that.AdImpression);
        equals = equals && this.Click.CompareData(that.Click);
        equals = equals && this.FraudInfo.CompareData(that.FraudInfo);
        return equals;
    }    // ~MemberwiseCompareDeep
    
    /// <summary>
    /// ToString
    /// </summary>
    public override string ToString()
    {
        return ToString(false, '\n');
    }

    /// <summary>
    /// ToString
    /// </summary>
    public  string ToString(bool valuesOnly, char separator)
    {
        System.Text.StringBuilder sb = new System.Text.StringBuilder();
   
        if (!valuesOnly)
        {
            sb.AppendFormat("{0}{1}{2}{1}", base.ToString(), separator, __internal.sc_structName);
        }
        
        string format = valuesOnly ? "{1}{2}" : "{0} = {1}{2}";
        sb.AppendFormat(format, __internal.s_PageView, this.PageView, separator);
        sb.AppendFormat(format, __internal.s_AdImpression, this.AdImpression, separator);
        sb.AppendFormat(format, __internal.s_Click, this.Click, separator);
        sb.AppendFormat(format, __internal.s_FraudInfo, this.FraudInfo, separator);
        
        return sb.ToString();
    } // ToString()

}; // class PSCFRSpark
} // namespace SparkSchema
